apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
        - name: iris-api
          image: gcr.io/steadfast-theme-457811-f1/iris-api:latest
          ports:
            - containerPort: 8200